### PR TITLE
Issue 31

### PR DESCRIPTION
**Pull request by afdesk**

### CODE REVIEW

**Comment by afdesk** [comment]
@jerbia ok, I'm testing it now.
I got next message: This message is too long to display here. Please visit the link to read the content.

**Comment by afdesk** [comment]
@afdesk can you show log? 
all records after:  Loading alerts configuration file...
I'll be useful. thanks

**Comment by afdesk** [comment]
@jerbia I asked log because I sent scan of `adrianotto/centos6:latest` to slack and teams 
```
2020/06/05 17:57:21 Starting Slack plugin "my-slack"....
2020/06/05 17:57:21 Starting Email plugin "email"...
2020/06/05 17:57:21 Starting MS Teams plugin "ms-team"....
2020/06/05 17:57:21 Starting WebServer....
2020/06/05 17:57:21 Listening for HTTPS on 0.0.0.0:8445
2020/06/05 17:57:21 Listening for HTTP on 0.0.0.0:8082 
2020/06/05 17:57:54 Sending message via "ms-team"
2020/06/05 17:57:54 Sending to MS Teams via "ms-team"...
2020/06/05 17:57:55 Sending to MS Teams via "ms-team" was successful!
2020/06/05 17:57:55 Sending message via "my-slack"
2020/06/05 17:57:55 Sending via Slack "my-slack"
2020/06/05 17:57:57 Sending [1/3 part] to "my-slack" was successful!
2020/06/05 17:57:59 Sending [2/3 part] to "my-slack" was successful!
2020/06/05 17:57:59 Sending [3/3 part] to "my-slack" was successful!
2020/06/05 17:57:59 Sending via Slack "my-slack" was successful!
2020/06/05 17:57:59 Sending message via "email"
2020/06/05 17:58:02 Email was sent successfully!
```

**Comment by jerbia** [comment]
You are right. In the logs I do see that Teams was sent. Any reason it will take 8 seconds from the Slack to the JIRA actions? You might need to use Go Routines to send the messages simultaneously, otherwise you will not be able to deal with load of WebHook requests.

2020/06/05 11:26:56 Sending message via "my-slack"
2020/06/05 11:26:56 Sending via Slack "my-slack"
2020/06/05 11:26:57 Sending [1/1 part] to "my-slack" was successful!
2020/06/05 11:26:57 Sending via Slack "my-slack" was successful!
2020/06/05 11:26:57 Sending message via "my-teams"
2020/06/05 11:26:57 Sending to MS Teams via "my-teams"...
2020/06/05 11:26:58 Sending to MS Teams via "my-teams" was successful!
2020/06/05 11:26:58 Sending message via "amir-jira"
2020/06/05 11:26:59 added 1 custom fields to issue.
2020/06/05 11:27:00 Created new jira issue 10093
2020/06/05 11:27:00 Sending message via "amir-aqua"
2020/06/05 11:27:04 Email was sent successfully!

**Comment by afdesk** [comment]
>. Any reason it will take 8 seconds from the Slack to the JIRA actions? You might need to use Go Routines to send the messages simultaneously, otherwise you will not be able to deal with load of WebHook requests.

Sure, You are right. I missed this moment.

**Comment by jerbia** [comment]
Can you also send a smaller message to avoid the "this message is too long to display here. Please visit the link to read the content." message?

**Pull request merged**
